name: Try in Web IDE
description: Try in Web IDE
author: 'Red Hat'
branding:
  icon: circle
  color: red

inputs:
  github_token:
    description: 'GitHub token used to add PR comment and/or status check'
    required: true
  add_comment:
    description: If 'true', the action will add comments on each PR with a link to try the PR in Web IDE
    required: false
    default: 'true'
  add_status:
    description: If 'true', the action will add a PR status check on each PR with a link to try the PR in Web IDE
    required: false
    default: 'true'
  setup_remotes:
    description: >
      If 'true', the action will automatically configure remotes for the resulting workspace created by the Web IDE.

      Automatically configuring the remotes is useful for PRs made from a forked repository to an upstream repository.
      
      The Web IDE must be based on Eclipse Che® 7.60 for this feature.
    required: false
    default: 'false'
  web_ide_instance:
    description: The base url for the Web IDE instance
    required: false
    default: 'https://workspaces.openshift.com'
  comment_badge:
    description: The badge url for the comment created when 'add_comment' is 'true'
    required: false
    default: 'https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940'

runs:
  using: node16
  main: dist/index.js
